services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kumora
      MYSQL_USER: kumora
      MYSQL_PASSWORD: kumora
    ports:
      - "3309:3306"
    volumes:
      - mysql_datas_kumora:/var/lib/mysql

volumes:
  mysql_datas_kumora: