name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push with Kaniko
        uses: aevea/action-kaniko@master
        with:
          image: camelia-studio/kumora
          username: camelia
          password: camelia
          registry: ${{ secrets.REGISTRY_SERVER }}
          tag: ${{ gitea.ref_name }}
          tag_with_latest: true