
name: Apply PHP CS Fixer

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga@sha256:5cfb9c812528bbafd614ca16a7d48e7ab35421d930cab611e815d6bfe8f07bfa
        with:
          args: --diff --dry-run

