on: [push, pull_request]


env:
  APP_ENV: dev

name: rector
jobs:
  rector:
    name: Rector
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP with pre-release PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: php-actions/composer@v6
    - name: Cache Symfony dev container
      run: |
        php bin/console cache:warmup --env=dev
    - name: Run Rector
      run: vendor/bin/rector --dry-run
