on: [push, pull_request]
name: rector
jobs:
  rector:
    name: Rector
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rector
      uses: zingimmick/rector-action@0.0.3
      with:
        args: --dry-run
